name: rag-pipeline

services:
  pgvector-db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
    ports: [ "5432:5432" ]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
volumes:
  pgdata: