### POST chat
POST http://localhost:8081/api/chat/ask
content-type: application/json

{
  "text": "Does PostgreSQL support additional data types, other than standard ones?"
}

### POST extract
POST http://localhost:8081/api/chat/extract
content-type: application/json

{
  "text": "Pay 1250 EUR to DE89370400440532013000 by 2026-03-03"
}

###
